name: Build and Push Docker Image

on:
  push:
    branches:
      - master  # Solo se activa en la rama "master"
  pull_request:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Paso 1: Clonar el repositorio
    - name: Check out code
      uses: actions/checkout@v3

    # Paso 2: Iniciar sesión en Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Paso 3: Construir la imagen Docker
    - name: Build Docker Image
      run: docker build -t andresmonroy/paginaweb:latest .

    # Paso 4: Subir la imagen a Docker Hub
    - name: Push Docker Image
      run: docker push andresmonroy/paginaweb:latest