name: ci

on:
    push:
        branches: [master]


jobs:
    build:
        runs-on: ubuntu-latest
        steps:
           - name: "Mostrar Ejecucion"
             run: echo "Hola, Despliegue continuo"